# Generated by Django 4.2 on 2023-05-03 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0003_alter_category_options_alter_women_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='women',
            old_name='is_puplished',
            new_name='is_published',
        ),
    ]
